### ISSUE TITLE
mmWave Studio needed for raw data collection?

### ISSUE THREAD

**Issue by Youras** [moodoki/iwr_raw_rosnode#2]
Hello and thanks for sharing this interesting project. 
I am wondering if your project runs on a Linux machine (e.g. ubuntu) in order to collect raw data.

So far I was only able to collect pre-processed data as sparse point clouds from a IWR 6843 board (basically the [TI ROS Package](https://dev.ti.com/tirex/explore/node?node=AOVWxEvg-HcESecamNaaLg__VLyFKFf__LATEST) )

I only know that a custom raw data collection with the DCA1000 via ethernet is possible if it was previously configured by mmWave Studio, which is only available on Windows, one good example is the [OpenRadar](https://github.com/PreSenseRadar/OpenRadar) project.

It would be awesome if your project runs completely without mmWave Studio and raw data collection would work on a linux computer, since this is what I am looking for.

Best
Raschid

**Comment by moodoki** [comment]
Hi, thanks for your interest in our project.

Yes, I'm using Ubuntu for the project.

mmWave Studio is not required. Our driver is able to configure the DCA1000 via ethernet similar to how mmWave studio does it. 

I don't have the IWR 6843 board, so I'm not sure if there's any difference in the DCA1000 configuration. Please try it out and see if it works for you.

**Comment by pens0001** [comment]
> Hi, thanks for your interest in our project.
> 
> Yes, I'm using Ubuntu for the project.
> 
> mmWave Studio is not required. Our driver is able to configure the DCA1000 via ethernet similar to how mmWave studio does it.
> 
> I don't have the IWR 6843 board, so I'm not sure if there's any difference in the DCA1000 configuration. Please try it out and see if it works for you.

How do I configure the DCA1000 via ethernet using your drives? I'm not sure where to start this process. I'm also able to get point cloud data, but I'm interested in the raw data for further processing.

**Comment by moodoki** [comment]
The DCA1000 is configured automatically when starting the ROS node. No additional configuration is needed. 

If you want to use it without ROS, the code that's used to configure DCA1000 is in https://github.com/moodoki/iwr_raw_rosnode/blob/master/mmWave/scripts/mmWave_class_noQt.py starting at line 115.

Feel free to adapt it for your needs

**Comment by Max1274** [comment]
Hi, I'm also interested in using raw radar data without mmWave Studio. From my understanding, you need to initialize DCA1000 but also need to start the radar module. Is this step also included in the file you mentioned above?

**Comment by moodoki** [comment]
yup, it is, radar commands are sent over a serial connection, it's configured right after the DCA is intialized

**Comment by DRDRDR123** [comment]
Hi, thanks for your project. It would be really useful for me if I could read the raw data with a ubuntu system through this project.
However, I wonder how should I start to use it. Saying I have attached the DCA1000 and IWR1443 on my PC. Which code should I run first to configure the DCA1000?
