### ISSUE TITLE
error when startSensor through serial

### ISSUE THREAD

**Issue by huangjuite** [moodoki/iwr_raw_rosnode#3]
Hello and thanks for sharing this interesting project.
I am trying to run your code on my AWR1843BOOST with DCA100EVM.
I'm able to connect and set both radar and capture card.
But it failed at starting the radar when sending "sensorStart" command to the radar board.
The response message is "Erro".
I have check the radar board is functioning using mmwave demo visualizer.
Have you experience any similar problems like this?

**Comment by moodoki** [comment]
I'm not too sure. It might be that the serial port isn't configured correctly. You might need to change the serial port that's used, especially if your system already have other serial ports.

**Comment by bjs3118** [comment]
Hi @huangjuite , did you ever manage to find a solution for this error? I am getting a similar issue.
