### ISSUE TITLE
convert raw data to pointcloud format

### ISSUE THREAD

**Issue by Nitinsn29** [moodoki/iwr_raw_rosnode#4]
Hi,
I have downloaded radical dataset, the data's are in rosbag format, which consists of radar_data : [mmWave/dataframe : int16[] data], how to convert that raw data into point clouds(.pcd format)?
Thanks in advance

**Comment by moodoki** [comment]
We do not work with point clouds, thus we don't have code for this conversion. However, it should not be difficult to do beamforming, followed by CFAR or other radar detection algorithms to obtain point clouds.
