### ISSUE TITLE
CFAR 

### ISSUE THREAD

**Issue by Nitinsn29** [moodoki/iwr_raw_rosnode#5]
In https://github.com/moodoki/iwr_raw_rosnode/blob/master/mmWave/scripts/fft_viz.py after finding range _doppler and range_azimuth, how to find elevation_fft and do CFAR?

**Comment by moodoki** [comment]
We intend for this just as a visualization of the data being captured. CFAR isn't included as it's not the goal of this node. Our radar signal processing code is in this project https://github.com/moodoki/radical_sdk. 
As for elevation, these radars only have 2 elevation channels, thus FFT is not the best choice for beam forming.
