### ISSUE TITLE
Radar hardware configuration

### ISSUE THREAD

**Issue by NicNedwob** [moodoki/iwr_raw_rosnode#6]
Hi there, I hope you are well.
I've been trying to use your mmWave python class (I have made some adjustments for my purposes) to get raw data out of the DCA1000 without mmwave studio. With you code I have successfully setup the DCA and can send commands to it and receive expected responses, however I am not receiving any data packets from DCA1000 (confirmed with wireshark) once recording has started. I would imagine this is because the radar sensor is not starting. I thought perhaps my radar (IWR6843 with mmwaveICboost) could be in the incorrect mux and switch configuration and was wondering if you could confirm how your radar was configured.
Best regards 
Nicholas Bowden

**Comment by moodoki** [comment]
After setting up the DCA1000, I sent commands to the IWR1443 over a serial connection. I suppose you'll need to do the same thing with the IWR6843?
