### ISSUE TITLE
DCA timeout

### ISSUE THREAD

**Issue by ghost** [moodoki/iwr_raw_rosnode#7]
Hello,
I am running the following command : `roslaunch mmWave radar_rd_fft_viz.launch`

However, I keep getting a time out message : 

`WARNING: Package name "mmWave" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[rosout-1]: started with pid [10823]
started core service [/rosout]
process[xwr1xxx-2]: started with pid [10826]
process[xwr1xxx_rd_viz-3]: started with pid [10830]
SET UP DCA
3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0]
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
timed out
`

As a side note, I have set the static ip of my machine to 192.168.33.30, but I am not able to ping the DCA which is 192.168.33.180. Should I be able to ping it?

**Comment by moodoki** [comment]
You should be able to ping the DCA. It looks like you are unable to communicate with the DCA and this is what's causing the timeouts.
