### ISSUE TITLE
MSS Info

### ISSUE THREAD

**Issue by yuvalg1987** [moodoki/iwr_raw_rosnode#8]
Hi, 

Can you provide some information regarding the attached MSS as the defualt SDK Demo MSS does not support LVDS data transfer.
In addition, do you know where can I find some documentation regarding MSS structure/code for future developmnet?

Thanks
Yuval

**Comment by moodoki** [comment]
I've gotten all my information from TI's E2E  [forums](https://e2e.ti.com/support/sensors-group/sensors/f/sensors-forum) and the SDK documentation on TI's website.
